# Generated by Django 4.1.13 on 2024-08-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancscp', models.IntegerField()),
                ('libgvr', models.CharField(max_length=255)),
                ('libloc', models.CharField(max_length=255)),
                ('libprd', models.CharField(max_length=255)),
                ('datliv', models.DateTimeField()),
                ('qteprd', models.FloatField()),
                ('prixHT', models.FloatField()),
                ('lag1_previous_order', models.FloatField()),
                ('lag3_previous_order', models.FloatField()),
                ('lag6_previous_order', models.FloatField()),
                ('lag9_previous_order', models.FloatField()),
            ],
        ),
    ]
