# Generated by Django 4.1.13 on 2024-08-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BO1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienthistory',
            old_name='ancscp',
            new_name='ANCSCP',
        ),
        migrations.RenameField(
            model_name='clienthistory',
            old_name='datliv',
            new_name='DATLIV',
        ),
        migrations.RenameField(
            model_name='clienthistory',
            old_name='libgvr',
            new_name='LIBGVR',
        ),
        migrations.RenameField(
            model_name='clienthistory',
            old_name='libloc',
            new_name='LIBLOC',
        ),
        migrations.RenameField(
            model_name='clienthistory',
            old_name='libprd',
            new_name='LIBPRD',
        ),
        migrations.RenameField(
            model_name='clienthistory',
            old_name='qteprd',
            new_name='QTEPRD',
        ),
    ]
