# Generated by Django 4.1.13 on 2024-08-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO1', '0002_rename_ancscp_clienthistory_ancscp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANCSCP', models.IntegerField()),
                ('DATLIV', models.DateTimeField()),
                ('LIBGVR', models.CharField(max_length=255)),
                ('LIBLOC', models.CharField(max_length=255)),
                ('LIBPRD', models.CharField(max_length=255)),
                ('prixHT', models.FloatField()),
                ('lag1_previous_order', models.FloatField()),
                ('lag3_previous_order', models.FloatField()),
                ('lag6_previous_order', models.FloatField()),
                ('lag9_previous_order', models.FloatField()),
                ('prediction', models.FloatField()),
            ],
        ),
    ]
