# Generated by Django 4.1.13 on 2024-08-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BO1', '0005_rename_last_quantity_deivered_predictnextcall_last_quantity_delivered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredictNextCall',
            new_name='PredictNextCallClient',
        ),
    ]
