# Generated by Django 4.1.13 on 2024-08-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BO1', '0008_nextcalldelivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NextCallDelivery',
        ),
    ]
