# Generated by Django 4.1.13 on 2024-08-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BO1', '0009_delete_nextcalldelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictNextCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANCSCP', models.IntegerField()),
                ('DATLIV', models.DateTimeField()),
                ('LIBGVR', models.CharField(max_length=255)),
                ('LIBLOC', models.CharField(max_length=255)),
                ('LIBPRD', models.CharField(max_length=255)),
                ('prixHT', models.FloatField()),
                ('last_quantity_delivered', models.FloatField()),
                ('next_call', models.FloatField()),
            ],
        ),
    ]
