# Generated by Django 4.1.13 on 2024-08-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BO1', '0010_predictnextcall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictnextcall',
            name='last_quantity_delivered',
        ),
    ]
